name: CI pipeline

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag java-magazine:latest
      - name: Create PDF / Word
        run: docker run -v ${PWD}/article:/documents java-magazine 'asciidoctor -r asciidoctor-pdf -b pdf *.adoc; for f in *.adoc; do asciidoctor --backend docbook --out-file - ${f} | pandoc --from docbook --to docx --output ${f%.adoc}.docx; done'
      - name: List files
        run: ls -alrt ${PWD}/article
      - name: Upload introduction PDF
        uses: actions/upload-artifact@v1
        with:
          name: introduction PDF
          path: article/introduction_article.pdf
      - name: Upload advanced PDF
        uses: actions/upload-artifact@v1
        with:
          name: advanced PDF
          path: article/advanced_article.pdf
      - name: Upload introduction Word
        uses: actions/upload-artifact@v1
        with:
          name: introduction Word
          path: article/introduction_article.docx
      - name: advanced Word
        uses: actions/upload-artifact@v1
        with:
          name: Word
          path: article/advanced_article.docx