name: CI pipeline

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag java-magazine:latest
      - name: Create PDF / Word
        run: docker run -v ${PWD}/article:/documents java-magazine 'asciidoctor --backend docbook --out-file - introduction_article.adoc | pandoc --from docbook --to docx --output out.docx'
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: PDF
          path: /documents/introduction_article.pdf
